### ISSUE TITLE
why not implement this based on ngx_lua

### ISSUE THREAD

**Issue by fankeke** [ZigzagAK/ngx_api_gateway#1]

**Comment by ZigzagAK** [comment]
Hello, @fankeke !

Functional:
Some of features is not possible to implement with lua nginx module.
* embedded configuration templating.
* add/remove real nginx upstreams dynamically without reloads (balancer_by_lua is a very bad approach).
* effective dynamically configurable worker shared router.

Performance is a critical part of routing requests process.
I already have another implementation with LUA. Switching context between LUA and C breaks jit. Lua string too slow. Lua GC is not fast. For very high load (>20000k) lua may (not must) be a "bootleneck".

At my main work we have around 3200 peers and active healthchecks written in LUA have very very bad performance. To prevent problem [ngx_dynamic_healthcheck](https://github.com/ZigzagAK/ngx_dynamic_healthcheck) module was written. All statistics a rewritten in clear C. Some of logic implemented with LUA, but all system things rewritten in C because Lua have high overhead.

**Comment by ZigzagAK** [comment]
And another one gateway implemented with LUA is not interesting. This implementation is not requires embed lua. This is more lightweight than lua implementation.

**Comment by ZigzagAK** [comment]
Somewhere I use [TDS](https://github.com/torch/tds) for out of heap tables and arrays manipulation. In the case of usage very large tables performance increased up to 10x times.

**Comment by fankeke** [comment]
awesome! appreciate that
